export const NOTIFCATIONS = "NOTIFCATIONS";
export const CLEARNOTIFICATIONS = "CLEARNOTIFICATIONS";
export const CLEARSINGLENOTIFICATION = "CLEARSINGLENOTIFICATION";
export const READSINGLE = "READSINGLE";
